### ISSUE TITLE
binding.get('') returns the same value as binding.get()

### ISSUE THREAD

**Issue by gerad** [moreartyjs/moreartyjs#101]
Calling `binding.get('')` (with an empty string) returns the same value as `binding.get()` - the value of the binding at the root path

Instead, I would expect to return the value of the binding with the empty string subpath.

https://jsfiddle.net/npsdsum6/

![create a new fiddle - jsfiddle 2015-11-30 18-23-39](https://cloud.githubusercontent.com/assets/27563/11490657/8d7205d8-978f-11e5-9aa3-2a7309882feb.png)

**Comment by Tvaroh** [comment]
I think this is as expected. Why would you need empty string keys?

**Comment by gerad** [comment]
It's more the absence of the empty string key we were counting on… our data structure was something like this:

```javascript
binding.set(Immutable.Map({
  key1: object1,
  key2: object2,
  key3: object3
})
```

and we checking whether the key was present in the data structure before doing some logic

```javascript
function doSomething(key) {
  if (binding.get(key)) {
   // do something
  }
}
```

the logic broke when a blank string key was passed

**Comment by mbektimirov** [comment]
Use `getIn` on immutable object:
```javascript
binding.get().getIn(key.split('.'))
```
