### ISSUE TITLE
Binding access in render function - question

### ISSUE THREAD

**Issue by mkopylec** [moreartyjs/moreartyjs#105]
Hi, I am new to React and MoreartyJS.
Is there any way to access the binding in components `render` function?
If no, how can I make the `render` function to be dependent on binding?

**Comment by ElectricCookie** [comment]
You simply include the Morearty Mixin in your Component and then call `this.getDefaultBinding()`. I haven't had a look at morearty for ages, not to disencourage you from using it, but there's some newer implementations of architectures like Redux, which are way better documented, but require a little bit more work than Morearty. Anyways good luck with React & Morearty!

**Comment by mkopylec** [comment]
Thanks for your answer, I solved my problem by passing `binding` property to nested React components.
