### ISSUE TITLE
Use with react-router

### ISSUE THREAD

**Issue by klimashkin** [moreartyjs/moreartyjs#13]
Hello! Is it possible to use morearty with [React Router](https://github.com/rackt/react-router)?

**Comment by tume** [comment]
Any updates on this? I have been also looking for a good router. Would be nice to at least have more real-world examples how to do that (todomvc with director is kind of too simple).

**Comment by Tvaroh** [comment]
Experimenting with this in the linked issue thread. In progress for now.

**Comment by dfguo** [comment]
+1, do we have a working example on this? Thanks!

**Comment by Tvaroh** [comment]
Here is some [gist](https://gist.github.com/CptLemming/a9292f95db799f11541d) which seems to work.

**Comment by Tvaroh** [comment]
I've created react-hot-boilerplate based [example](https://github.com/Tvaroh/morearty-react-router) ported from the above gist.

**Comment by Download** [comment]
@Tvaroh Unfortunately `react-router` changed it's API... The example is not working anymore with the 1.0 version.

I added this issue to the example project:
https://github.com/moreartyjs/morearty-react-router/issues/1
