### ISSUE TITLE
ReactCSSTransitionGroup causes:  Error: Invariant Violation: findComponentRoot 

### ISSUE THREAD

**Issue by andru** [moreartyjs/moreartyjs#40]
Using Morearty 0.7.4 (sorry, npm is giving me trouble trying to update to 0.7.5)

Is React `CSSTransitionGroup` supported? If not, are there alternatives for in/out transitions?

When I wrap my elements in a React `CSSTransitionGroup`, I get the following error:

```
 Morearty: render error. Continuing. 
Error: Invariant Violation: findComponentRoot(..., .0.2.0.1.0.$=1$51142015-01-07T00=0234=0229=01238Z:0): Unable to find element. 
This probably means the DOM was unexpectedly mutated (e.g., by the browser), usually due to forgetting a <tbody> when using tables, nesting tags like <form>, <p>, or <a>, or using non-SVG elements in an <svg> parent. 
Try inspecting the child nodes of the element with React ID ``. {framesToPop: 1, stack: (...), message: "Invariant Violation: findComponentRoot(..., .0.2.0… the child nodes of the element with React ID ``."}
```

Just incase it's a bug, I should add that my document ids contain `.` characters, which has caused me a headache or two elsewhere when working with keypaths as strings instead of arrays.

**Comment by andru** [comment]
Managed to update to `0.7.5` and now the error is just:

```
Morearty: render error. Continuing.Morearty.js:291 catchingRenderErrorsMorearty.js:300 render
```

**Comment by Tvaroh** [comment]
@andru thanks for the report.

Actually, I don't know right now, I need to investigate how this stuff works. Will look into that.

**Comment by andru** [comment]
@Tvaroh trying to get a jsFiddle up, but morearty is giving weird errors - is there a CDN copy anywhere? I don't see it on cdnjs.

**Comment by andru** [comment]
I can't isolate this behaviour, but nor am I having any success at getting rid of it in my application code. I suggest this gets closed for now; if I can reproduce it as a bug in Morearty I'll follow it up later.

**Comment by Tvaroh** [comment]
@andru great, thank you.
