### ISSUE TITLE
Initial state for meta binding difficulties

### ISSUE THREAD

**Issue by kapooostin** [moreartyjs/moreartyjs#41]
I'm trying to setup meta for binding together with initial state of the app:
```js
var ctx = Morearty.createContext(
    {...},
    {...}
)
```
Then inside App component in `render` method:
```js
var binding = this.getDefaultBinding();
var meta = binding.meta();
console.log( meta.get() ); // undefined
```

What am I doing wrong? The meta binding itsef contains this data, I can see it in Chrome Inspector.

**Comment by Tvaroh** [comment]
Hello.

Meta binding uses format like this:

```javascript
{
  __meta__: <root meta>,
  foo: {
    __meta__: <foo meta>,
    bar: {
      __meta__: <bar meta>
    }
  }
}
```

Meta argument probably wasn't meant to be hand-crafted but serialized from existing meta binding populated by the app. So, if you want to create meta-state manually you need to use the format above.

**Comment by Tvaroh** [comment]
I will update the wiki to reflect this info.

**Comment by kapooostin** [comment]
Great, thank you!
