### ISSUE TITLE
npm bug?

### ISSUE THREAD

**Issue by gilbox** [moreartyjs/moreartyjs#46]
Has anyone seen this?

    npm install morearty -S
    rm -rf node_modules/
    npm install

      npm ERR! peerinvalid The package immutable does not satisfy its siblings' peerDependencies requirements!
      npm ERR! peerinvalid Peer morearty@0.7.7 wants immutable@~3.5.x

Modifying the package.json from ` "immutable": "^3.5.0",` to ` "immutable": "~3.5.0",` fixes it

**Comment by Tvaroh** [comment]
Is it reproducible with 0.7.8 version as well?

**Comment by gilbox** [comment]
Seems to be OK with 0.7.8.
