### ISSUE TITLE
suggested patterns for updating matching objects in different parts of the binding/tree

### ISSUE THREAD

**Issue by jotto** [moreartyjs/moreartyjs#47]
With a binding/tree that has the same object in multiple places, are there any suggested patterns for updating the matching objects?

example:
```javascript
myTree = {
  comment: {user: {id: 1, name: 'John'}},
  blog: {user: {id: 1, name: 'John'}}
}
binding.set(Immutable.fromJS(myTree))
binding.sub('blog.user').set(Immutable.fromJS({name: 'Johnny'}))
```

Now blog.user no longer matches comment.user, but what if we wanted those identical `comment.user` and `blog.user` immutable objects to be simultaneously updated?

**Comment by Tvaroh** [comment]
Hello. You can [atomically update](https://github.com/moreartyjs/moreartyjs/wiki/Binding#transactions-and-chaining) binding values:

```javascript
binding.atomically().
  set('comment.user', user).
  set('blog.user', user).
  commit();
```

**Comment by Tvaroh** [comment]
@jotto has it worked for you?

**Comment by jotto** [comment]
@Tvaroh, yes - that definitely works. Than you.

I was hoping someone had devised a pattern or best practice for keeping matching objects all over the tree in sync without managing them manually.
