### ISSUE TITLE
IE8 Support?

### ISSUE THREAD

**Issue by gilbox** [moreartyjs/moreartyjs#51]
What is the intended level of IE support? immutable.js seems to support IE8 with es5shim.

- If I submit an IE8 bug report will anyone pursue it?
- If I submit an IE8 bug fix will it be seriously considered?

I haven't done any IE8 testing yet, just wondering what's on the roadmap.

**Comment by Tvaroh** [comment]
IE8 doesn't support Array.prototype.map/filter and so on. I think supporting IE9 and higher would be more reasonable. Do you really need IE8 supported?

**Comment by gilbox** [comment]
es5shim takes care of map, filter, etc. If it was up to me evergreen browsers would be the only support I *need*... unfortunately it's not up to me.

**Comment by Tvaroh** [comment]
Theses changes are trivial, I will push 'em tomorrow. Also it's a good idea to have `remove` synonim for `delete`.

**Comment by Tvaroh** [comment]
By the way you can create pull request if you like.

**Comment by gilbox** [comment]
https://github.com/moreartyjs/moreartyjs/pull/52

**Comment by Tvaroh** [comment]
Published in 0.7.9.

**Comment by gilbox** [comment]
:dancers:
