### ISSUE TITLE
Object.freeze on prototype before adding delete property

### ISSUE THREAD

**Issue by gilbox** [moreartyjs/moreartyjs#56]
I had an error (which isn't actually an issue anymore) crop up in therubyracer (v8 engine) after nuking `node_modules/` which lead me to the `Object.freeze`ing of prototypes. [My PR](https://github.com/moreartyjs/moreartyjs/commit/1b74515ff37e0be8d87fff8a1da0e97f2032b9fb#diff-0bb262c0cfb1290fef6a4c294443b323R549) added the `delete` property on the prototype *after* [the freeze](
https://github.com/moreartyjs/moreartyjs/blob/1b74515ff37e0be8d87fff8a1da0e97f2032b9fb/src/Binding.js#L320), which makes no sense that it ever worked.

Any ideas?

**Comment by Tvaroh** [comment]
Since tests test only `remove` method, the absence of `delete` probably wasn't noticed. :)

**Comment by gilbox** [comment]
Thanks. I'll increase the test coverage and fix it.
