### ISSUE TITLE
Req for info: testing with jest

### ISSUE THREAD

**Issue by p14n** [moreartyjs/moreartyjs#59]
Hi, I'm trying to start a simple test using jest and TestUtils, but I'm clearly doing it wrong as I'm dropping into an infinite loop (test fails with max call stack exceeded):
```javascript
var Morearty = require('morearty');
var React = require('react/addons');
var TopHeader = require('../js/components.js');
var TestUtils = React.addons.TestUtils;

  var Ctx = Morearty.createContext({
    initialState: {
      headerText: 'Off'
    }
  });

describe('TopHeader', function() {
  it('should appear on load', function() {

    var bootstrap = Ctx.bootstrap(TopHeader) //TopHeader is a react component with mixins: [Morearty.Mixin]

    var header = TestUtils.renderIntoDocument(
      React.createElement(bootstrap)
    );

    // Verify that it's Off by default
    var label = TestUtils.findRenderedDOMComponentWithTag(
      header, 'h1');
    expect(label.getDOMNode().textContent).toEqual('Off');

  });
});
```
The TopHeader component for completeness:
```javascript
var React = window.React = require('react/addons');
var Morearty = require('morearty');
var el = React.createElement

var TopHeader = React.createClass({
  displayName: 'TopHeader',
  mixins: [Morearty.Mixin],
  render: function(){
    var binding = this.getDefaultBinding();
    var text = binding.sub("headerText")
    return el("h1",{},text)
  }
})

module.exports = TopHeader 
```
I'm assuming the approach is wrong - any advice gratefully received.  If it looks like the right approach I'll do some more digging in to the problem.

Cheers,
Dean

**Comment by gilbox** [comment]
I've been wondering how others have been testing with Morearty as well. fwiw, here is my working approach

Ideally, I'd like my test to be as simple as...

```
    var binding = mockBinding('hello');

    instance = TestUtils.renderIntoDocument(
      <HelloWorld binding={binding} />
    );
```

It can be achieved with the following function:

```
// Creates a Morearty Binding from a string, number, boolean, or object
module.exports.mockBinding = function(v) {
  var t = typeof v;
  if (t === 'string' || t === 'number' || t === 'boolean') {
    return  Morearty.createContext({ initialState: { v } }).getBinding().sub('v');
  } else {
    return Morearty.createContext({ initialState: v }).getBinding();
  }
};
```

It works for simple use cases, unfortunately for complex usage it fails because no bootstrap means no morearty [context](https://www.tildedave.com/2014/11/15/introduction-to-contexts-in-react-js.html). This can be solved with:

```// Creates a Morearty Binding from a string, number, boolean, or object
module.exports.mockBinding = function(v) {
  var t = typeof v;
  if (t === 'string' || t === 'number' || t === 'boolean') {
    ctx = Morearty.createContext({ initialState: { v } });
    return ctx.getBinding().sub('v');
  } else {
    ctx = Morearty.createContext({ initialState: v });
    return ctx.getBinding();
  }
};

module.exports.mockRender = function (instanceFn) {
  return React.withContext({morearty: ctx}, function () {
    return TestUtils.renderIntoDocument(instanceFn());
  });
};
```

and now the test becomes:

```
    var binding = mockBinding('hello');

    instance = mockRender(() =>
      <HelloWorld binding={binding} />
    );
```

BTW, I tried jest and gave it up because it was too slow. Using jasmine with karma along with `rewire-webpack`. Morearty really could use some documentation related to unit testing...

**Comment by p14n** [comment]
Cheers, I'll give that a go.

**Comment by p14n** [comment]
All works well, thanks.  Jest is fast for me - I only have a couple of components at the moment but it's 2s from save to test results using watch.  Or maybe you have a 100ms feedback loop?

**Comment by p14n** [comment]
Oh, and the infinite loop was me passing a binding instead of a value into the component:
```javascript
    var text = binding.sub("headerText") //Should be .get not .sub
    return el("h1",{},text)
```

**Comment by gilbox** [comment]
Startup time doesn't concern me too much. I just leave Jasmine running. Currently I have 70 tests, just ran them all in `0.287s` (most of the tests are for components using Morearty). There's [a long-open issue about Jest slowness](https://github.com/facebook/jest/issues/116), if you solve it I'm sure many would benefit.

**Comment by dfguo** [comment]
@gilbox where is the best place to include mockBinding and mockRender so that all jest tests will have them? Thanks!

**Comment by gilbox** [comment]
I just create a separate file like `test-utils.js` and include it from each test.

```
var testUtils = require('../test-utils.js');

// now use testUtils.mockRender and testUtils.mockBinding...
```

**Comment by dfguo** [comment]
works! thanks!
