### ISSUE TITLE
Ability to copy a context on a sub state only

### ISSUE THREAD

**Issue by jbe456** [moreartyjs/moreartyjs#60]
**The use case:**
All my components does not share the same ancestors. Thus I have to bootstrap multiple  components. I do so by using `Ctx.copy()` method. But some component are only related to a sub part of the global state. And because the Ctx is always associated to the global state, this component will re-render everytime there is a modification in the state regardless if this modification is relevant to the component.

**A possible solution:**
Currently, when doing `Ctx.copy()`, it creates a new context with exactly the same underlying bindings :
```
  copy: function () {
    return new Context(this._stateBinding, this._metaBinding, this._options);
  }
```

I would like to be able to "copy" but only for a sub-binding, giving a path for example:
```
  copy: function (subpath) {
   //TODO what about options?
    return new Context(this._stateBinding.sub(subPath), this._metaBinding.sub(subPath), this._options);
  }
```

Tested locally and worked as expected.

**Comment by Tvaroh** [comment]
Thanks for the report. I see no problems adding `subpath` arg to `copy`. Will include this in the next minor release.

**Comment by jbe456** [comment]
I just ran into an issue with the `isChanged` method from the binding.

```
isChanged: function (alternativeBackingValue, compare) {
    var value = this.get();
    if (!Util.undefinedOrNull(alternativeBackingValue)) {
      var alternativeValue =
        this._path.length > 0 ? alternativeBackingValue.getIn(this._path) : alternativeBackingValue;
      return !(compare ? compare(value, alternativeValue) : value === alternativeValue);
    } else {
      return !Util.undefinedOrNull(this._sharedInternals.backingValue);
    }
```

The children are now re-rendered everytime because `shouldComponentUpdate` returns true
```
execute.1.Object.freeze.isChanged
execute.5.bindingChanged
execute.5.stateChanged
execute.5.module.exports.Mixin.shouldComponentUpdate.shouldComponentUpdate
execute.5.module.exports.Mixin.shouldComponentUpdate
```

The issue is that the binding still have the absolute path, whereas the `alternativeBackingValue`has now only a sub part of the state (because it comes from a context looking only at a subpart of it). Thus, this `alternativeBackingValue.getIn(this._path)` returns `undefined`.

**Comment by gilbox** [comment]
+1 re: broken shouldComponentUpdate... do you have a fix @jbe456 ?

**Comment by gilbox** [comment]
I'm unable to make a test that demonstrates a `shouldComponentUpdate` bug with a normal binding. However I was able to fashion **[a unit test with a meta binding that incorrectly calculates `shouldComponentUpdate`](https://github.com/gilbox/moreartyjs/commit/14fdb41a39b8fc4aa73c90190278b0b4a241dbc2)**... But isn't a meta binding just a subset of a regular binding?. Or maybe I'm misunderstanding how meta bindings work.

**Comment by Tvaroh** [comment]
I have pushed optional subpath support. Seems to work fine. @jbe456 could you try and confirm that is works in your scenario? You'll need to build manually using `npm run build`.

**Comment by Tvaroh** [comment]
@jbe456, closing this for now. Feel free to re-open if needed.
