### ISSUE TITLE
Custom functions undefined after bootstraping the react class

### ISSUE THREAD

**Issue by jbe456** [moreartyjs/moreartyjs#61]
**The issue:**

The current `bootstrap` function wrap the given root component into another React class:
```
bootstrap: function (rootComp, reactContext) {
    var ctx = this;

    var effectiveReactContext = reactContext || {};
    effectiveReactContext.morearty = ctx;

    var root = React.withContext(effectiveReactContext, function () {
      return React.createFactory(rootComp)({ binding: ctx.getBinding() });
    });

    return React.createClass({
      displayName: 'Bootstrap',

      componentWillMount: function () {
        ctx.init(this);
      },

      render: function () {
        return root;
      }
    });
  }
```

The consequence is that any function defined in the `rootComp` object is not available after the bootstrap, although it is the case if you simply create the react class.

More precisely, if `A` is your initial object and the following method is defined `A.mymethod`, then `mymethod` will be available in `React.render(React.createElement(React.createClass(A)), target)`

**A dirty solution:**
Looking at the code, the only goal of the wrapper is to add : 
```
      componentWillMount: function () {
        ctx.init(this);
      }
```

Thus, supposing that :
`var rootComp = React.createClass(rootCompInner);`

we could do the following:
```
bootstrapObject: function (rootCompInner, additionalProps,  reactContext) {
    var ctx = this;

    //merge the props, I use lodash here
    const props = _.defaults(additionalProps || {}, {binding: ctx.getBinding()});

    var effectiveReactContext = reactContext || {};
    effectiveReactContext.morearty = ctx;

    rootCompInner.mixins.push(Morearty.Mixin);
    rootCompInner.mixins.push({
        componentWillMount: function () {
          ctx.init(this);
        }
    });

    var root = React.withContext(effectiveReactContext, function () {
      var rootComp = React.createClass(rootCompInner);
      return React.createFactory(rootComp)(props);
    });

    return root;
  }
```

This would return directly a React element (that's why I gave the ability to add props), so it would be a different output type than the current bootstrap method.

The *dirty* part is that we modify the mixins of the incoming object ... maybe we could workaround it by checking existing mixins.

**Comment by gilbox** [comment]
We already have to add `Morearty.Mixin` to every component, maybe instead of doing it in the `bootstrapObject` function, require that the user add `Morearty.BootstrapMixin` instead of `Morearty.Mixin` to any component that will be bootstrapped.

**Comment by jbe456** [comment]
That could be a possibility. The drawback is that in some case, when you create a component, you don't necessarily know if you will be using it as a root component, a regular one or both... so to me it's the same problem as the first alternative.

**Comment by Tvaroh** [comment]
By the way, `bootstrap` method is just a helper, you're not forced to use it.

**Comment by jbe456** [comment]
Well I guess with the new way of defining React context in 0.13 (where we have to wrap the component into a class with a `getChildContext` method), this issue is not relevant anymore.
