### ISSUE TITLE
shouldComponentUpdate bug with meta() binding

### ISSUE THREAD

**Issue by gilbox** [moreartyjs/moreartyjs#62]
This discussion started [here](https://github.com/moreartyjs/moreartyjs/issues/60#issuecomment-76473766)...

 I'm unable to make a test that demonstrates a `shouldComponentUpdate` bug with a normal binding. However I was able to fashion **[a unit test with a meta binding that incorrectly calculates `shouldComponentUpdate`](https://github.com/gilbox/moreartyjs/commit/14fdb41a39b8fc4aa73c90190278b0b4a241dbc2)**... But isn't a meta binding just a subset of a regular binding?. Or maybe I'm misunderstanding how meta bindings work.

*update*: I also noticed that changing a meta state will only incorrectly trigger update if I also change some (any) non-meta state.

**Comment by Tvaroh** [comment]
Gil, can you confirm it's working fine now?

**Comment by gilbox** [comment]
Everything looks good so far. Tests pass and no more bugs related to this in my project. Nice work! :+1:
