### ISSUE TITLE
Morearty tests trigger error logs

### ISSUE THREAD

**Issue by jbe456** [moreartyjs/moreartyjs#68]
Running the Morearty tests locally, I have the following logs: 
```
Error details: Invariant Violation: dangerouslyReplaceNodeWithMarkup(...): Cannot render markup in a worker thread. Make sure `window` and `document` are available globally before requiring React when unit testing or use React.renderToString for server rendering. 
```

This is because you import `React` before settings the global `window` and `document` variables.

In `Morearty.js` for example, you do it correctly line 14 :
```
var requireReact = function () {
var window = domino.createWindow('<div><div id="root"></div><div id="altRoot"></div></div>');
global.window = window;
global.document = window.document;
global.navigator = global.window.navigator;
return require('react/addons');
};
var React = requireReact();
```

BUT you import `Morearty` (https://github.com/moreartyjs/moreartyjs/blob/master/test/Morearty.js#L6) which requires internally `React` : https://github.com/moreartyjs/moreartyjs/blob/master/src/Morearty.js#L7

So `React` is loaded BEFORE the globals are defined.

Weirdly, this error does not prevent the tests to fail.

**Comment by Tvaroh** [comment]
@jbe456, could you make a pull request which fixes this problem? I saw that error but couldn't wrap my head around it.

**Comment by Tvaroh** [comment]
Tests are now fixed in master.
