### ISSUE TITLE
Morearty v0.7.13 is missing the index.js file when doing npm install

### ISSUE THREAD

**Issue by cesarp** [moreartyjs/moreartyjs#70]
We were doing npm install in a new project that has morearty version as ~0.7.12 in its package.json file and it installed 0.7.13 which was just released and the build failed.

Webpack said *Error: Cannot resolve module 'morearty' in...* after looking inside our node_modules/morearty folder we noticed that the index.js file is missing in 0.7.13. After installing 0.7.12 everything worked again.

**Comment by Tvaroh** [comment]
I encountered this before, this is probably some NPM bug since index.js is in place. Published 0.7.14. Thanks for the report.
