### ISSUE TITLE
Immutable Bindings?

### ISSUE THREAD

**Issue by gilbox** [moreartyjs/moreartyjs#75]
Any thoughts on immutable bindings? It would be a huge refactor, but I think that a lot of the complexity of SCU, and the rendering algorithm in general comes from the fact that bindings themselves are mutable.

**Comment by Tvaroh** [comment]
Gil, what's the use case for such bindings? Bindings are by nature mutable. Immutable data can be passed to components directly in props.

**Comment by gilbox** [comment]
I just think it would simplify the internals of Morearty. Like you said, bindings can then simply be passed as props and SCU becomes almost as simple as the PureRenderMixin. No longer any need for special handling for observed props. And I think observed bindings become much simpler as well because there is no longer a need for `savePreviousState`.

It's not an original idea. Omniscient uses immutable bindings.

**Comment by Tvaroh** [comment]
Gil, I didn't use Omniscient, could you provide an example? Are immutable bindings an addition for ordinary bindings, or a replacement? How one would change state that is mutable by nature using immutable bindings? What concretely is immutable in immutable bindings?

**Comment by gilbox** [comment]
I've never used omniscient either, but it's an interesting project...

The idea is that any `set` or `update` operation on a binding would return a new cursor. [From their docs:](http://omniscientjs.github.io/guides/02-editing-using-immutable-cursors-with-omniscient/)

```
// New sub cursor for top node, and update that value
var cursor = structure.cursor();

var subCursor = cursor.cursor(['some', 'place', 'in', 'tree']);

var newSubCursor = subCursor.update(/* ... */);

newSubCursor //=> new data
subCursor //=> old data

// and even:
cursor.cursor(['some', 'place', 'in', 'tree']) //=> old data

// this is due to:
cursor //=> old data
```

> Are immutable bindings an addition for ordinary bindings, or a replacement?

They are a replacement

> How one would change state that is mutable by nature using immutable bindings? 

I don't think I understand this question. Do you mean that the state of the binding itself is mutable by nature?

> What concretely is immutable in immutable bindings?

My understanding is that the reference to an immutable-js object that the binding wraps is immutable.

**Comment by gilbox** [comment]
having second thoughts
