### ISSUE TITLE
Test with JSDom

### ISSUE THREAD

**Issue by mrjjwright** [moreartyjs/moreartyjs#78]
Hi, great lib!  I am testing with mocha and jsdom.  I am not getting any render triggered on updating a binding.  I know Morearty uses `setTimeout` if `requestAnimFrame` is unavailable, which it would be in jsdom.  This should be working right?   Is there any other reason it wouldn't be working, it works in the browser.

**Comment by gilbox** [comment]
Maybe this is a dumb question, but are you using an asynchronous test? Otherwise the test will end before render() happens.

**Comment by mrjjwright** [comment]
No I am not, this is my first day in Mocha.  I am sorry for the false alarm.  I will look up the docs on that. :)
