### ISSUE TITLE
Working with history

### ISSUE THREAD

**Issue by Theadd** [moreartyjs/moreartyjs#81]
You're really doing a great job! :100:
Working with the tree of state bindings was... ok, but by just writing a ~couple more lines to work with the history module was awesome!

Could it be possible to _stack|group|merge|remove|*_ some points of state in history so when calling undo/redo it treats those states as a single one instead of iterating each one for every history call?

Maybe by disabling/enabling the history before/after a .set() or .update? I've tried with `{ notify: false }` but I didn't notice anything different:
```jsx
this.getDefaultBinding().atomically().
  set("meshMap", Imm.List(collection._items)).
  commit({ notify: false });
this.forceUpdate();
```
Maybe because `this.getDefaultBinding()` was a sub-binding of the one initialized with history instead of the history one?

**Comment by Tvaroh** [comment]
Hello.

If I understood correctly, you need to consider some set of changes as an atomic single history record. Doesn't putting those changes in a single transaction give that behavior?

**Comment by Theadd** [comment]
let me try it in a couple of hours. I did not imagine that an atomic transaction could be started in one component render method and commited in a nested different one.

**Comment by Tvaroh** [comment]
Yep, it should be possible. Not sure how convenient it is though.

**Comment by Tvaroh** [comment]
@Theadd I re-thinked your problem and looks like I was wrong. If you don't commit transaction, components down won't be rendered.

**Comment by Theadd** [comment]
well, I've used forceUpdate() + observedProps (passing the transaction context as prop) but since I don't commit that transaction, the default binding in nested components does not reflect those changes so nested components doesn't even need to update.

I might have to refactor that part a little bit to be able to update the binding within the same component.
