### ISSUE TITLE
React Warning when remove() OB in componentWillUnmount

### ISSUE THREAD

**Issue by gilbox** [moreartyjs/moreartyjs#82]
Is this a bug?

```
  // get a warning about forceUpdate of an unmounted component
  componentWillUnmount() {
    ob.remove();
  }
```

```
  // no warning
  componentWillUnmount() {
    ob.atomically().remove().commit({notify: false});
  }
```

we could fix this by checking c.isMounted() in the render function but is this a case where the correct thing to do is the second approach?

**Comment by Tvaroh** [comment]
Gil, sorry for long response. A similar issue reported here #83. You're right, `isMounted` check is required, like on root component. Will add one.

**Comment by Tvaroh** [comment]
Added check to prevent warning in `0.7.18`.
