### ISSUE TITLE
Update queue introduced in 0.7.15 completly broke my application

### ISSUE THREAD

**Issue by valff** [moreartyjs/moreartyjs#83]
When upgrade from 0.7.14 to any version up to 0.7.17, I get a lot of such warnings in console:

    "Warning: forceUpdate(...): Can only update a mounted or mounting component. This usually means you called forceUpdate() on an unmounted component. This is a no-op."

Application components are not updated, or updated with delay in unpredictable manner. I suppose this breaking changes is caused by the new update queue algorithm introduced in 0.7.15.
Using latest react 0.13.3.

**Comment by Tvaroh** [comment]
@valff, it's hard to diagnose such a problem without details. Can you paste a minimal failing code example, please?

**Comment by valff** [comment]
Ok, I fixed my own bugs, which were unapparent in 0.7.14. Application is no longer broken, but still showing warnings in console.

Here is the [example](https://gist.github.com/valff/b613aba5db099a0000fe) (click more than 2 times).

**Comment by Tvaroh** [comment]
Added check to prevent warning in `0.7.18`. Thank you, @valff!
