### ISSUE TITLE
Random binding listeners are removing on unmount

### ISSUE THREAD

**Issue by valff** [moreartyjs/moreartyjs#85]
https://github.com/moreartyjs/moreartyjs/blob/master/src/Morearty.js#L702
This chunk of code seems not working as intended. Listeners are not removing properly. Moreover, because listener ids are incremental, random listeners for default binding may be removed. Therefore I think this is highly critical issue.

**Comment by Tvaroh** [comment]
Thanks, will look into this asap.

**Comment by Tvaroh** [comment]
@valff, could you please clarify why listener aren't removed properly? And why random listeners may be removed?

**Comment by valff** [comment]
@Tvaroh, because all listeners are removed from one default binding, not from binding, to which they are attached. And random listener may be removed, because listener ids may be collided for two distinct bindings.
I propose to store listener remover closures instead of `_observedListenerIds`. Should I make pull request?

**Comment by valff** [comment]
I see this was a regression from 0.7.15. Will create pull request soon.

**Comment by Tvaroh** [comment]
@valff, thank you so much! Just merged the code. Awesome!

**Comment by Tvaroh** [comment]
Does current behavior cause some problems?

**Comment by valff** [comment]
Thank you for merging! I found that `addBindingListener` have similar problem when listening to other than default binding. It has strange implementation, and I want to fix it.

Have a question about `shouldRemoveListeners()`, why we ever need it? If I don't want listerers to be removed, I use `binding.addListener(...)` instead. I propose to remove this method from API.

**Comment by Tvaroh** [comment]
Regarding `shouldRemove listeners`, it protects from cases when multiple components bind to same state section.

**Comment by Tvaroh** [comment]
Regarding `addBindingListener` - yep, looks like it needs to be fixed too.

**Comment by Tvaroh** [comment]
@valff, in which situation listener ids may collide? IIRC, this should be avoided.

**Comment by valff** [comment]
What happens when multiple components bind to same section? Isn't it safe to add listeners at the same binding, and removing them independently?

Listener ids may collide in normal and meta bindings. They are not share `_sharedInternals`.

**Comment by Tvaroh** [comment]
> They are not sharing _sharedInternals.

I see. That's what should be fixed. We're following the wrong path.

**Comment by Tvaroh** [comment]
Will look into PR a bit later.

**Comment by Tvaroh** [comment]
@valff, regarding `shouldRemoveListeners`.

Two components on a page bind to the same state section, and one of them uses `addBindingListener`. What if another component is removed from the page? Without `shouldRemoveListeners` it would remove listeners attached to the first component as well (since bindings bound to same path are same object instance).

**Comment by Tvaroh** [comment]
@valff, regarding `shouldRemoveListeners`: with your updated implementation this check may be safely removed. Just did it. Thank you!

**Comment by Tvaroh** [comment]
Release in `0.7.21`.
