### ISSUE TITLE
Components with observed bindings are not receiving new props

### ISSUE THREAD

**Issue by valff** [moreartyjs/moreartyjs#89]
Opening this new issue, because #86 is probably wrong. The issue is not primarily in render order, but in receiving new props from parent component. Not sure how to fix it properly, please see the updated test case.

**Comment by Tvaroh** [comment]
I suppose update props cannot be known without rendering the parent, and probable parent's parent, and so on. We may render from the top first, and then render observed bindings, as you suggested. The downside is probably worse performance. What do you think, @gilbox?

**Comment by Tvaroh** [comment]
We also might add a component property to signal that component isn't interested in props updates. This would solve a case when a single observed binding backed components changes deep inside the hierarchy and we want to skip redundant re-rendering from the top.

**Comment by Tvaroh** [comment]
So, the new syntax is:

```javascript
observedBindings: [binding1, { binding: binding2, renderFirst: true }, binding3]
```

'Render-first' bindings will be rendered before top-down rendering. Ordinary observed bindings will be rendered last.

**Comment by Tvaroh** [comment]
So, the new syntax is:

```javascript
observedBindings: [binding1, { binding: binding2, renderFirst: true }, binding3]
```

'Render-first' bindings will be rendered before top-down rendering. Ordinary observed bindings will be rendered last. Still thinking if this could be improved.

**Comment by Tvaroh** [comment]
After some experiments I realized that it's all redundant. Let top-down rendering be the first and all optimizations left for direct React's component API manipulations.

**Comment by Tvaroh** [comment]
Released in `0.7.21`.

**Comment by gilbox** [comment]
If I understand correctly, when you combine side-loading via observed bindings and top-down-loading via props then components must be rendered top-down otherwise a component that is force-rendered might use old props. However, I'm not sure if your fix completely handles this case. More specifically, in the following loop:

```
            self._componentQueue.forEach(function (c) {
              forceUpdate(c);
              savePreviousState(c);
            });
```

isn't it possible for the components to be rendered out-of-order?

**Comment by Tvaroh** [comment]
Regarding your example, probably you're right.

**Comment by gilbox** [comment]
Thought about this some more.

I think I was wrong. I forgot that the component queue is ordered by componentQueueId and higher id's are always children of lesser ids. 

https://github.com/moreartyjs/moreartyjs/blob/master/src/Morearty.js#L182

**Comment by Tvaroh** [comment]
Nice! I was thinking similarly.
