### ISSUE TITLE
console.error messages to exception reporter?

### ISSUE THREAD

**Issue by dfguo** [moreartyjs/moreartyjs#90]
console.error when morearty has some issue rendering is super useful when in development mode, but in production, we actually want to use exception reporting services like Bugsnag or Errorception to catch these errors. However, these services don't report console.error messages; they only report exceptions. 

I'm trying to understand what's the best way for me to get Errorception report the exception. I can monkey-patch console.error so it sends message to Errorception. Or I can fork Morearty and monkey patch it so it throws exception instead of using console.error. Thoughts?

**Comment by mbektimirov** [comment]
As I know, window.onerror handler could track all exceptions globally on the page. If doesn't solve your problem, ping us again.

**Comment by dfguo** [comment]
onerror handler doesn't take care of ```console.error```

**Comment by Tvaroh** [comment]
@dfguo, how other libraries cope with this?

**Comment by dfguo** [comment]
Hi @Tvaroh I have looked around and didn't find much useful information. Why did we use console.error in the first place? It is to log the error while not interrupt the rendering? For now, I hijacked console.error.

**Comment by Tvaroh** [comment]
Yep, it's just to log an error and continue. Is there a better way?

**Comment by dfguo** [comment]
@Tvaroh I don't know any other way too, honestly. Hijacking it works fine for me, so I'm closing the issue now.
