### ISSUE TITLE
ES6 and Mixins

### ISSUE THREAD

**Issue by gerherz** [moreartyjs/moreartyjs#92]
Using React components as ES6 classes, it's not possible to use mixins:
> Unfortunately, we will not launch any mixin support for ES6 classes in React. That would defeat the purpose of only using idiomatic JavaScript concept.

Is it possible to use morearty.js with ES6 classes? If not, are you planning to implement this in the near future?

**Comment by Tvaroh** [comment]
@gerherz, actually, I don't know but there is some related discussion in #84.

**Comment by Pierrickouw** [comment]
@gerherz I am currently doing it with [react-mixin](https://github.com/brigand/react-mixin).

Something like that:
```js
import React from 'react';
import Morearty from 'morearty';
import reactMixin from 'react-mixin';

class YourComponent extends React.Component {
     //your component
}

reactMixin.onClass(YourComponent, Morearty.Mixin);
```
You can do this in all your components or use it as a base component and then extend from here.

I don't know if there is a better way, but this is a workaround if you want to use morearty and ES6 class.

**Comment by gerherz** [comment]
Great, I didn't know the react-mixin library. Thanks!
