### ISSUE TITLE
Observed property change doesn't trigger rerender

### ISSUE THREAD

**Issue by eguneys** [moreartyjs/moreartyjs#93]
I use react-dnd and I have a droptarget component:

```

const stoneTarget = {
  drop() {
    console.log('dropped');
  },
  // this triggers everytime the dragged item is on drop target
  hover(props, monitor, component) {

    const delta = {
      x: Math.random(),
      y: Math.random()
    };

    const overPositionBinding = visualStore.bindings.isOverDiscardMiniBox;

    // I set the data everytime the item is being dragged
    overPositionBinding.update(function(immutableValue) {
      return immutableValue.set('position', delta);
    });

  }
};

@DropTarget(ItemTypes.STONE, stoneTarget, collect)
class DiscardMiniBoxSequenceArea extends React.Component {
  mixins: [Morearty.Mixin]

  componentDidMount() {
    // If I add this change listener it is called repeatedly on hover, so this works
    visualStore.bindings.isOverDiscardMiniBox.addListener(function(changes) {
      console.log(Math.random())
    });
  }

  observedBindings: [gameStore.bindings.discardMiniBoxSequence,
  visualStore.bindings.isOverDiscardMiniBox]

  render() {
     // however render is not called
  }

});
```

When I drag the item over drop target, it calls the `hover` function and I set a binding inside it.

I expect it to cause a rerender but it doesn't render. 

However if I explicitly add a change listener it is called.

**Comment by Tvaroh** [comment]
Hello.

Didn't dig too much, but I don't see `observedProps` property defined in your code.

**Comment by eguneys** [comment]
I am using [observed bindings](https://github.com/moreartyjs/moreartyjs/wiki/Authoring%20components#using-observed-bindings), I don't use any props do I have to use them?

**Comment by eguneys** [comment]
Actually I can't use mixins in es6, I tried this solution https://github.com/moreartyjs/moreartyjs/issues/92, but I can't get morearty work with my components why?

**Comment by Tvaroh** [comment]
Observed bindings are not observed props. That's why I asked: topic is misleading.

**Comment by Tvaroh** [comment]
It's hard to tell something based on your code. Minimal reproducing runnable example, e.g. on jsfiddle. would be helpful.

**Comment by eguneys** [comment]
Good documentation too much trouble though, I switch to redux which is way more awesome than this.
